run:
  timeout: 5m
  tests: true
linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - goimports
    - errcheck
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
linters-settings:
  gofmt:
    simplify: true
  errcheck:
    exclude-functions:
      - (*encoding/json.Encoder).Encode
      - (net/http.ResponseWriter).Write
