blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/RouXx67/PulseUp/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/RouXx67/PulseUp/wiki
    about: Check the wiki for guides and documentation
