name: Build and Publish Docker Agent Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'cmd/pulse-docker-agent/**'
      - 'internal/dockeragent/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/docker-agent-image.yml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-agent-image:
    name: Build & Push agent image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version
        id: version
        run: |
          VERSION=$(tr -d '\n' < VERSION)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push agent image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: agent_runtime
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/pulse-docker-agent:latest
            ghcr.io/${{ github.repository_owner }}/pulse-docker-agent:${{ steps.version.outputs.version }}
